### ISSUE TITLE
Problema

### ISSUE THREAD

**Issue by jackmakiyama** [PHPMT/api-express#1]
Qual será o problema que vamos resolver?

**Comment by f0ntana** [comment]
vamos fazer um boilerplate? deixar pronto uma api com integração de permissões, usuários e colocar JWT,  ou alguma outra ideia?

**Comment by enieber** [comment]
acho que o primeiro problema que poderiamos resolver é tratamento de rotas

**Comment by jackmakiyama** [comment]
Opa, problema digo um caso da realidade que possamos representar com uma API.

**Comment by enieber** [comment]
no caso poderiamos fazer uma mini "rede social" onde só seria possivel interagir nela atravez da api...

**Comment by jackmakiyama** [comment]
@enieber @f0ntana bisbilhotando meus gist aqui achei uma lista que comecei a tempos de livros freem, então, o que acham de fazermos uma API de livros?

[Aqui está a lista](https://gist.github.com/jackmakiyama/8922f0be80b795849856).

**Comment by f0ntana** [comment]
interessante ... podemos fazer algo para verificar o livro do dia do packtpub

**Comment by enieber** [comment]
## API de livros

@PHPMT/members  podemos começar o desenvolvimento da api de livros

**Comment by enieber** [comment]
@jackmakiyama o problema ja foi definido, não seria melhor abrir uma outra issue para descrever melhor o que precisa ser feito?

**Comment by jackmakiyama** [comment]
é que não rolou um deal ainda. kkkkk

**Comment by enieber** [comment]
e se fizessemos uma api para gerenciamento de cursos para o Open Schol BR ?

https://github.com/openschoolbr/forum/issues/2

**Comment by f0ntana** [comment]
Com a treta rolando quase que eu li WebSchool kkkkk 

podemos começar com a dos livros.. acho demais..

💯

**Comment by enieber** [comment]
oque acha de fazermos uma votação @jackmakiyama ?  

votamos entre:
:a:  Api de livros
:b: Api de gerenciamento de cursos

:ab: Para outra ideia   e ai comenta com a outra ideia

cade o povo @PHPMT/members ?

**Comment by enieber** [comment]
eu vou de :b:

**Comment by jackmakiyama** [comment]
🅰️

**Comment by f0ntana** [comment]
🅰️

Vamos fazer o primeiro depois ampliamos se não não fazemos nada

**Comment by enieber** [comment]
@PHPMT/members bora fechar essa issue com o problema definido como  **Api de livros**?

**Comment by enieber** [comment]
@jackmakiyama e @f0ntana bora fechar essa issue e começar a desenvolver?

**Comment by jackmakiyama** [comment]
Por mim, bora.
